services:
  esphome:
    container_name: esphome
    image: ghcr.io/esphome/esphome
    volumes:
      - $PWD:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    privileged: true
    network_mode: host
    environment:
      - USERNAME=test
      - PASSWORD=ChangeMe
